Revert "unit tests failing with AttributeError: module 'cupyx' has no attribute 'lapack'"
This reverts commit 50048bad8ad392e2e4d6b3819f6801607c05bac0.